[feat] 공공서비스 이미지를 띄운다 (#24)
hyunji1203/SeoulGongGong pull request #37
Opened 2024-04-27 21:09 UTC by whk06061

## 📌 관련 이슈
- #24 

## 🛠️ 작업 내용
- [X] 공공서비스 Domain Type, Ui Type 을 생성한다.
- [X] UiServiceType 에 맞는 아이콘을 띄운다.
- [X] 필터 옵션에 UiServiceType 을 적용한다.

## 🎯 리뷰 포인트

## 💻 미완료 태스크

2024-04-30 10:20 UTC, pingu244 approved these changes
굿굿굿 
고생많으셨습니당~!!

2024-05-02 10:36 UTC, hyunji1203 approved these changes
고생많아써용 혜경씌~~~👍
아이콘 너무 이쁩니다!!!!!!!!
와근데 지금 서비스 리스트쪽에서 아래와 같은 에러가 나고 있어서 직접 확인은 못했어요🥹
이거 dev branch에서도 이러는것같아서 여기 PR 문제는 아니고 따로 서버나 어디서 문제가 있는 듯 합니당 따흑

<img width="700"  src="https://github.com/hyunji1203/SeoulGongGong/assets/83613106/f72d71cb-e41a-48d9-9f16-d99ec66c4003">

2024-05-02 12:38 UTC, hyunji1203 requested changes
에러 나는 원인 찾았습니다!!

2024-05-02 12:38 UTC, hyunji1203 commented on app/src/main/java/com/seoulfitu/android/data/local/entity/SportsServiceScrapEntity.kt
> +    val type:SportsServiceType
Entity에는 class 형으로 저장이 될 수 없어서 그래서 여기에서 에러가 뜨는것 같아요!🥹
아마 Domain은 해당 클래스 타입으로 해놓고 Mapper에서 Entity로 바꿔줄때 String으로 바꿔줘야 할것 같슴다!
```suggestion
    val type: String
```

2024-05-04 14:38 UTC, whk06061 commented on app/src/main/java/com/seoulfitu/android/data/local/entity/SportsServiceScrapEntity.kt
> +    val type:SportsServiceType
제가 할 때도 그 오류가 났었는데요 이거 아마 뽀또씌 폰에 깔려있던 앱의 데이터베이스 타입이 현재 브랜치랑 안맞아서 저런 오류가 났었던 걸로 기억합니다!!! 😭😭😭 그래서 앱 지우고 다시 깔면 정상적으로 실행이 될 것 같습니다!!! 😍😍😍😍 한번 다시 확인 부탁드립니댱 히히히

2024-05-04 15:19 UTC, hyunji1203 commented on app/src/main/java/com/seoulfitu/android/data/local/entity/SportsServiceScrapEntity.kt
> +    val type:SportsServiceType
꺄올!!!! 됐어요!!!! 그래서 그랬구나!!! ㅋㅋㅋㅋㅋ
친절한 설명 감사합니당😘 내 가상 기기 문제였던 걸루><

2024-05-04 15:19 UTC, hyunji1203 approved these changes
아이콘 이뻐용😍

2024-05-07 01:23 UTC, merged